# -*- coding: utf-8 -*-
"""Nil.eigendvek.eigen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Yf9ynRndebk6_8qDukqqf6p2u5lvZhb
"""

import numpy as np
A = np.array([[4, 1],
             [2 ,3]])
nilaieigen, vektoreigen = np.linalg.eig(A)
print("nilaieigen:")
print(nilaieigen)
print("\nvektoreigen:")
print(vektoreigen)

import numpy as np
B = np.array ([[5, 8],
              [6 ,9]])
nilaieigen, vektoreigen = np.linalg.eig(B)
print("nilaieigen:")
print(nilaieigen)
print("\nvektoreigen:")
print(vektoreigen)

import numpy as np
A = np.array ([[4, 1],
              [-2 ,3]])
nilaieigen, vektoreigen = np.linalg.eig(A)
print("nilaieigen:")
print(nilaieigen)
print("\nvektoreigen:")
print(vektoreigen)

import numpy as np
A = np.array ([[-2, -1],
              [5 ,2]])
nilaieigen, vektoreigen = np.linalg.eig(A)
print("nilaieigen:")
print(nilaieigen)
print("\nvektoreigen:")
print(vektoreigen)