# -*- coding: utf-8 -*-
"""Pertumbuhan_Logistik.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14VyRX7ezlPzDIuz8ZYtHV0W4PVK88R0D
"""

import numpy as np
import matplotlib.pyplot as plt

# Parameter model logistik berdasarkan artikel
K = 2014150  # Kapasitas batas lingkungan
P0 = 1138542  # Populasi awal
r_values = [0.008152866, 0.00555521, 0.002957554]  # Laju intrinsik
T = 100  # Rentang waktu simulasi

def logistic_solution(t, P0, r, K):
    return K / (1 + ((K - P0) / P0) * np.exp(-r * t))

# Waktu simulasi
t_values = np.linspace(0, T, 200)

plt.figure(figsize=(10, 6))
colors = ['green', 'red', 'blue']
labels = [f'r = {r}' for r in r_values]

# Substitusi parameter ke dalam solusi logistik
for r, color, label in zip(r_values, colors, labels):
    P_values = logistic_solution(t_values, P0, r, K)
    plt.plot(t_values + 1984, P_values, color=color, label=label)  # Geser waktu ke tahun sebenarnya

# Data populasi nyata berdasarkan artikel
actual_data = {
    1984: 1138542, 1990: 1200000, 2000: 1300000, 2010: 1400000  # Contoh data nyata
}

# Tambahkan data nyata ke grafik
actual_years = list(actual_data.keys())
actual_population = list(actual_data.values())
plt.scatter(actual_years, actual_population, color='black', marker='o', label='Data Nyata')

plt.xlabel('Tahun')
plt.ylabel('Populasi')
plt.title('Validasi Model Pertumbuhan Logistik dengan Data Nyata')
plt.legend()
plt.grid()
plt.show()